### ISSUE TITLE
EACCES: Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by jwalsh2me** [linode-solutions/mastodon-oca#2]
I was running into 500 errors and not able to update any profile images, follow people etc.  I think you need to update the Ansible Ruby scripts to handle this.  Also adding in some guidance on how to re-point to Object Storage would be great.  I am fluent in AWS, new to Linode.

The docker log from the container `live_web_1` was showing a permissions issue:

`InboxesController action=create status=500 error='Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/mastodon/public/system/cache'`

I ran `chown -R 991:991 /home/mastodon/livepublic/` and that resolved my issues.  

Ref --> [Maston GitHub Issue 18229](https://github.com/mastodon/mastodon/issues/18229)

**Comment by linode-solutions** [comment]
thank you for submitting this issue @jwalsh2me! Fix has been pushed https://github.com/linode-solutions/mastodon-oca/pull/3
