### ISSUE TITLE
healthcheck for Postgres uses nonexistent user

### ISSUE THREAD

**Issue by lno0** [linode-solutions/mastodon-oca#8]
I was getting an error on the health check for Postgres because on the provided docker-compose file the database is made with a user named mastodon but the healthcheck uses a user named postgres. 

You can correct this by replacing `test: ['CMD', 'pg_isready', '-U', 'postgres']` with `test: ['CMD', 'pg_isready', '-U', 'mastodon']`.

**Comment by tbaka** [comment]
Addressed with [pr 11](https://github.com/linode-solutions/mastodon-oca/pull/11).
