### ISSUE TITLE
'ansible_specdoc' ModuleNotFoundError during build process

### ISSUE THREAD

**Issue by RaoulHofmann** [linode-solutions/mastodon-oca#9]
Tried setting up an instance following the guide a few times and ran into this error each time.

> TASK [mastodon : create a domain] **********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible_specdoc'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1676606791.8480763-13130-215321695114481/AnsiballZ_domain.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1676606791.8480763-13130-215321695114481/AnsiballZ_domain.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1676606791.8480763-13130-215321695114481/AnsiballZ_domain.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.linode.cloud.plugins.modules.domain', init_globals=dict(_module_fqn='ansible_collections.linode.cloud.plugins.modules.domain', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_linode.cloud.domain_payload_u9nofybv/ansible_linode.cloud.domain_payload.zip/ansible_collections/linode/cloud/plugins/modules/domain.py\", line 11, in <module>\nModuleNotFoundError: No module named 'ansible_specdoc'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by hmorris3293** [comment]
thank you for the report @RaoulHofmann this has been resolved
